<a href="https://colab.research.google.com/github/Mrdecent08/Python-Lab/blob/main/Python_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
num = int(input("Enter a number :"))
if num == 1:
    look = "Python"
    print(look)
elif num == 2:
    look = "Day-1"
    print(look)

Enter a number :1
Python


In [ ]:
number = int(input("Enter a number: "))
if number>=0:
    print("Positive")
else:
    print("Negative")


Enter a number: 3
Positive


In [ ]:
num1 = int(input("Enter number 1: "))
num2 = int(input("Enter number 2: "))
num3 = int(input("Enter number 3: "))
if num1 >= num2 and num1 >= num3:
    print(str(num1)+ "is greatest")
elif num2 >= num1 and num2 >= num3:
    print(str(num2)+ "is greatest")
else:
    print(str(num3)+ "is greatest")


Enter number 1: 3
Enter number 2: 6
Enter number 3: 1
6is greatest


In [ ]:
sum =0
for i in range(1,51):
     if (i%2==0):
         print(i)
         sum += i
print("Sum is "+str(sum)) 

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
Sum is 650


In [ ]:
    print("Prime numbers are : ")
    for i in range(20,50):
      x = 0
      for j in range(1,i):
        if(i%j==0):
          x+=1
      if(x==1) :
        print(i)  

Prime numbers are : 
23
29
31
37
41
43
47


In [ ]:
a = input()
b = input()
print ('Before swapping valuyes of a and b are : '+a+' '+b)
a,b = b,a   
print ('After swapping valuyes of a and b are : '+a+' '+b)

3
6
Before swapping valuyes of a and b are : 3 6
After swapping valuyes of a and b are : 6 3


In [ ]:
def sm(a,b):
    return a+b , a*b
a= int(input())
b= int(input())
c , d = sm(a,b)
print('Sum is '+str(c)+' Multiplication value is '+str(d))

5
1
Sum is 6 Multiplication value is 5


In [ ]:
x = int(input())
y = int(input())
adder = lambda x,y: x+y
print("Sum is "+ str(adder(x,y)))

3
8
Sum is 11


In [ ]:
def intro(name , dept = 'cse'):
    print('Name is '+name+' and department is '+dept)
intro('Surya' , 'it')
intro('Aditya')

Name is Surya and department is it
Name is Aditya and department is cse


In [ ]:
n = int(input("Enter number of rows : "))
for i in range(1,n+1):
    for j in range(0,i):
        print('*' , end = '')
    print()

Enter number of rows : 4
*
**
***
****


In [ ]:
for i in (8,15,69):
   print(str(i)+" multliplication table") 
   for j in range(1,11):
       print(str(i)+" x "+str(j)+" = "+str(i*j))
   print()  

8 multliplication table
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80

15 multliplication table
15 x 1 = 15
15 x 2 = 30
15 x 3 = 45
15 x 4 = 60
15 x 5 = 75
15 x 6 = 90
15 x 7 = 105
15 x 8 = 120
15 x 9 = 135
15 x 10 = 150

69 multliplication table
69 x 1 = 69
69 x 2 = 138
69 x 3 = 207
69 x 4 = 276
69 x 5 = 345
69 x 6 = 414
69 x 7 = 483
69 x 8 = 552
69 x 9 = 621
69 x 10 = 690



In [ ]:
string = input()
length = 0
for i in string:
    length+=1
print('Length of string is '+str(length))

Srinivas
Length of string is 8


In [ ]:
a = input()
b = input()
print('Anagram') if sorted(a) == sorted(b) else print('Not a Anagram')

listen
netsli
Anagram


In [ ]:
string = input("Enter a string : ")
sub_string = input("Enter the sub-string : ")
if sub_string in string:
    print("Sub-string is present in the string.")
else:
    print("Sub-string is not present in the string.")

Enter a string : python
Enter the sub-string : py
Sub-string is present in the string.


In [ ]:
a = list(map(int,input("list 1 = ").split()))
b = list(map(int,input("list 2 = ").split()))
c = a+b
print("list after addition is",c)
c.insert(3,0)
print("list after inserting 0 at 3rd postion is",c)
print("list slicing from 1 to 5",c[1:6])

list 1 = 1 3 4
list 2 = 2 9 6
list after addition is [1, 3, 4, 2, 9, 6]
list after inserting 0 at 3rd postion is [1, 3, 4, 0, 2, 9, 6]
list slicing from 1 to 5 [3, 4, 0, 2, 9]


In [ ]:
a = list(map(int,input("list = ").split()))
print("length of list =",len(a))
print("max element in the list",max(a))
print("min element in the list",min(a))
print("list after sorting is ",sorted(a))
print("list slicing ",a[1:len(a)-2])

list = 2 5 1 9 8
length of list = 5
max element in the list 9
min element in the list 1
list after sorting is  [1, 2, 5, 8, 9]
list slicing  [5, 1]


In [ ]:
a = list(map(int,input("list = ").split()))
even = list(i for i in a if i%2==0)
print(even)

list = 2 3 4 5 6 7 8 10
[2, 4, 6, 8, 10]


In [ ]:
a=list(map(int,input("Enter space separated integers: ").split()))
b=list(map(int,input("Enter space separated integers: ").split()))
c=[]
m=len(a)
n=len(b)
if m>n:
    for i in range(n):
        c.append(a[i])
        c.append(b[i])
    for j in range(i+1,m):
        c.append(a[j])
else:
    for i in range(m):
        c.append(a[i])
        c.append(b[i])
    for j in range(i+1,n):
        c.append(b[j])
print(c)



Enter space separated integers: 1 3 5 7 9 
Enter space separated integers: 2 4 6 8
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
person1 = ("Himanshu", 24, "234 LosAngels America", "LosAngelsCol")
person2 = ("Rohith", 23, "34/56 BigStreet Banglore", "IIMB")
print("Tuple1 is "+ str(person1))
print("Tuple2 is "+ str(person2))
persons = person1 + person2
print("Concatenate Tuple is"+ str(person1))

Tuple1 is ('Himanshu', 24, '234 LosAngels America', 'LosAngelsCol')
Tuple2 is ('Rohith', 23, '34/56 BigStreet Banglore', 'IIMB')
Concatenate Tuple is('Himanshu', 24, '234 LosAngels America', 'LosAngelsCol')


In [ ]:
def count(str):
    d = dict()
    for i in str:
        if i in d.keys():
           d[i] += 1
        else :
            d[i] = 1
    return d 
l = []
a = count(input("enter string : "))
for i in range(int(input("enter n : "))):
    m =  max(a.values())
    l.append({key:val for key, val in a.items() if val == m})
    a = {key:val for key, val in a.items() if val != max(a.values())}
print(l)

In [ ]:
s = input("Enter a string: ")
vowels = "aeiouAEIOU"
count = 0
for i in s:
  if i in vowels:
    count=count+1
print("The number of vowels in "+s+" is "+str(count))

Enter a string: python
The number of vowels in python is 1


In [ ]:
str1 = input("Enter string1: ")
str2 = input("Enter string2: ")
common = set(str1).intersection(set(str2))
print("Common letters are :" + str(common))


Enter string1: python
Enter string2: pycharm
Common letters are :{'y', 'h', 'p'}


In [ ]:
vowels = "aeiouAEIOU"
def vowelcount(x):
  count = 0
  for i in s:
    if i in vowels:
      count=count+1
    return count

s = input("Enter multiple strings :").split()
print(sorted(s,key=vowelcount))

Enter multiple strings :pyhton java kotlin
['pyhton', 'java', 'kotlin']


In [ ]:
n = int(input("Enter a number: "))
dict = {}
for i in range(1,n+1):
    dict[i] = i**2
print("Required Dictionary is ")
print(dict)


Enter a number: 4
Required Dictionary is 
{1: 1, 2: 4, 3: 9, 4: 16}


In [ ]:
dict = {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
key = int(input("Enter a key: "))
if key in dict.keys():
    print("Key is present")
else:
    print("Key is not present")


Enter a key: 2
Key is present


In [ ]:
dict = {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
print("Initial Dictionary is :"+ str(dict))
key = int(input("Enter new key: "))
val = int(input("Enter a value: "))
dict[key] = val
print("Final Dictionary is :"+ str(dict))


Initial Dictionary is :{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
Enter new key: 6
Enter a value: 10
Final Dictionary is :{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 10}


In [ ]:
n = int(input("enter the size of dictionary : "))
sum = 0

dict = {}
for i in range(n):
    key = int(input("enter a new key : "))
    value = int(input("enter a new value : "))
    dict[key] = value
for i in dict.values():
  sum = sum+i
print("Sum is "+str(sum))  

enter the size of dictionary : 3
enter a new key : 1
enter a new value : 2
enter a new key : 2
enter a new value : 4
enter a new key : 3
enter a new value : 6
Sum is 12


In [ ]:
class person() :
    def __init__(self,name,age,weight,height) :
        self.name = name
        self.age = age
        self.weight = weight
        self.height = height
    def get_bmi_result(self):
        result = float(self.weight/pow(self.height,2))
        if result < 18.5 :
            return "underweight"
        elif result >=18.5 and result < 25:
            return "Healthy"   
        else :
            return "obese"
p = person(input("Enter name "),input("Enter age "),float(input("Enter weight in kgs ")),float(input("Enter height in meteres ")))            
print(p.get_bmi_result())

Enter name srinivas
Enter age 18
Enter weight in kgs 20
Enter height in meteres 128
underweight


In [ ]:
class Circle(object) :
    def __init__ (self,radius):
        self.radius = radius 
    def area(self) :
        return pow(self.radius,2)*3.14
    def perimeter(self) :
        return 6.28*self.radius
a = Circle(float(input("enter radius : ")))     
print("area of the circle is ",a.area())
print("perimeter of the circle is ",a.perimeter())

enter radius : 4
area of the circle is  50.24
perimeter of the circle is  25.12


In [ ]:
import numpy as np
a = np.array([1,2])
print("Array is")
print(a)
print("Appending a element in the array is ")
a = np.append(a,3)
print(a)
print("Inserting a element into array :")
a = np.insert(a,0,111)
print(a)
print("Reversing array :")
print(a[::-1])

Array is
[1 2]
Appending a element in the array is 
[1 2 3]
Inserting a element into array :
[111   1   2   3]
Reversing array :
[  3   2   1 111]


In [ ]:
import numpy as np
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
b = np.array([(1,0,0),(0,1,0),(0,0,1)])
print("Matrix Addition")
print(a+b)
print("Transpose of a matrix")
print(np.transpose(a))
print("Multiplication of matrices")
print(np.dot(a,b))

Matrix Addition
[[ 2  2  3]
 [ 4  6  6]
 [ 7  8 10]]
Transpose of a matrix
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Multiplication of matrices
[[1 2 3]
 [4 5 6]
 [7 8 9]]
